### ISSUE TITLE
[MINOR] Onpress en header

### ISSUE THREAD

**Issue by LcsGrz** [MatiasRamirez3097/cocktailfinder#10]
https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/screens/FinderScreen/index.js#L42

no veo bien pasar la navegacion por param, considero que es mejor pasar directamente la funcion que se va a ejecutar cuando se requiera algo de navigation, por que?

Ahora la app es chica y seguro la uses para hacer un goBack() pero en futuro podes tener un switch y no necesites hacer un goBack si no un navigate, o simplemente ejecutar algo antes del goBack

**Comment by MatiasRamirez3097** [comment]
solved
