### ISSUE TITLE
[CRITICAL] Colores

### ISSUE THREAD

**Issue by LcsGrz** [MatiasRamirez3097/cocktailfinder#13]
https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/Skeleton/index.js#L11

Los colores agregarlos a un archivo de constantes de colores y llamarlos de ahi.
No es necesario para el caso de colores constantes como 'black' - 'white' - 'red'

**Comment by LcsGrz** [comment]
ejemplo del archivo

export default {
love: "#420"
}

**Comment by MatiasRamirez3097** [comment]
solved
