### ISSUE TITLE
[recomended] Use of nested ternary

### ISSUE THREAD

**Issue by lauraisabelm** [MatiasRamirez3097/cocktailfinder#14]
https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/screens/FinderScreen/index.js#L58

Esta forma de renderizar código no es que esté mal pero de acuerdo a nuestra experiencia nos ha pasado que a veces no funciona muy bien tener varias ternarias anidadas entonces lo que hemos optado por hacer es crear una función en la que ponemos todos los casos de renderización en un if distinto. Ej:
If (loading) return skeleton;
if (error) return DefaultMsg;
y así sucesivamente

**Comment by MatiasRamirez3097** [comment]
Ya lo cambie por funcion, gracias por la recomendación!
