### ISSUE TITLE
[Minor] Super minor code improvement

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#2]
Esto es una bobada solamente, pero cuando solemos condicionar la plataforma verificamos si Platform.OS === 'iOS' ya que, bueno, es mas corto

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/DefaultFlatList/style.js#L27

**Comment by MatiasRamirez3097** [comment]
solved
