### ISSUE TITLE
[Minor] Remainder console.log

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#3]
Este es un issue que voy a crear una unica vez pero que se aplica a todas las instancias en el codigo: no dejar console.logs (u otras instancias de la consola) excepto en los casos donde se necesite debuggear un error

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/DefaultTextInput/index.js#L8

**Comment by MatiasRamirez3097** [comment]
solved
