### ISSUE TITLE
[Minor] Commented, unnecesary lines?

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#4]
Solo se deberian dejar comentarios cuando es necesario dejar un mensaje de ayuda para los dev o por algun otro motivo especial/funciones a futuro, pero nunca con codigo innecesario o deprecado

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/Skeleton/style.js#L5

**Comment by MatiasRamirez3097** [comment]
solved
