### ISSUE TITLE
[Minor] Important conditioners?

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#5]
Esto lo voy a dejar como reflexion solamente, es realmente necesario evaluar las dos condiciones en este caso? Comenta la respuesta y las alternativas posibles

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/header/index.js#L20

**Comment by MatiasRamirez3097** [comment]
Me parecio util para evitar dejar un boton sin efecto alguno por error, realmente no creo que sea del todo necesario.
Quiza sea mejor pasar una sola prop de tipo objeto con ambas propiedades.
