### ISSUE TITLE
[CRITICAL] Possibly missing exact propTypes declaration

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#7]
Me parecio estar viendo, en varias paginas del codigo, que faltaban ciertos parametros "required" en las declaraciones de PropTypes. Acordate de tener en cuenta y declarar que tipo de variables son requeridas y cuales no.

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/header/index.js#L47

**Comment by MatiasRamirez3097** [comment]
solved
