### ISSUE TITLE
[CRITICAL] Codigo duplicado

### ISSUE THREAD

**Issue by LcsGrz** [MatiasRamirez3097/cocktailfinder#8]
https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/screens/FinderScreen/index.js#L60

Para esto sugiero que hagas un array.map y ahorrar lineas de lo mismo, ejemplo

[1,2,3,4,5,6,7].map(() => (...))

**Comment by MatiasRamirez3097** [comment]
solved
