### ISSUE TITLE
[Minor] Default props

### ISSUE THREAD

**Issue by ale1313** [MatiasRamirez3097/cocktailfinder#9]
Te comento solamente esta linea pero se aplica a todos los estilos del codigo, acordate cuales props tienen ciertos valores por defecto y que no hacen falta declarar (salvo ciertos casos donde toman el estilo del padre). Por ej, alignItems y justifyContent tienen el valor por defecto de "flex-start"

https://github.com/MatiasRamirez3097/cocktailfinder/blob/2028f7297a242e07d088a037d9bbd733dd02fa69/src/components/header/style.js#L16

**Comment by MatiasRamirez3097** [comment]
solved
